import type { SupplierEligibleListing } from "../types";

/**
 * Deterministic fixture inventory for CARDTRADER_MODE=mock (local dev, CI, and this repo's
 * test suite). Never used in production — see CARDTRADER_MODE in src/server/env.ts.
 *
 * Card names, sets, card numbers, finishes, and prices are real — 180 Pokemon cards pulled
 * from the live Pokemon TCG API (api.pokemontcg.io) across 9 real sets (Base Set, Jungle,
 * Fossil, Team Rocket, Gym Heroes, Gym Challenge, Neo Genesis, Neo Discovery, Neo
 * Revelation), plus 20 Yu-Gi-Oh cards pulled from the live YGOPRODeck API
 * (db.ygoprodeck.com), each using that card's real current tcgplayer.com market price at
 * fetch time, converted to USDC base units. This is still a MOCK CardTrader listing
 * (quantities, seller IDs, and reliability scores below are synthetic — CardTrader itself
 * is not live yet, see AGENTS.md) — only the card identity and reference price are real,
 * snapshotted 2026-08-02. Re-run scripts/refresh-mock-inventory (see docs/DECISIONS.md) to
 * pull a fresh snapshot.
 *
 * Sampled from 799 real candidate cards, biased toward the cheap end ($0.05-a few dollars)
 * so Spark ($0.50) and Starter ($1) — the only two currently-unlocked tiers — have real
 * in-band fixtures for every rarity band instead of relying on pickFixtureForBand's
 * closest-match fallback. See rarity-bands.ts's pickFixtureForBand for the hard
 * absolute-price-cap filter that backs this up structurally, not just via density.
 */
export const MOCK_CARDTRADER_INVENTORY: SupplierEligibleListing[] = [
  {
    externalListingId: "mock-listing-001",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Super Potion",
    setName: "Base",
    cardNumber: "90/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 330000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-002",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Grass Energy",
    setName: "Base",
    cardNumber: "99/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 450000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-003",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Psychic Energy",
    setName: "Base",
    cardNumber: "101/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 510000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-004",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Berry",
    setName: "Neo Genesis",
    cardNumber: "99/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 600000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-005",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "PlusPower",
    setName: "Base",
    cardNumber: "84/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 720000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-006",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Poliwag",
    setName: "Base",
    cardNumber: "59/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 800000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-007",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Sandshrew",
    setName: "Base",
    cardNumber: "62/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 900000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-008",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Lightning Energy",
    setName: "Neo Genesis",
    cardNumber: "109/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 980000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-009",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Onix",
    setName: "Base",
    cardNumber: "56/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 1040000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-010",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Diglett",
    setName: "Base",
    cardNumber: "47/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 1150000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-011",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Defender",
    setName: "Base",
    cardNumber: "80/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 1240000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-012",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Balloon Berry",
    setName: "Neo Revelation",
    cardNumber: "60/64",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 1300000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-013",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Fire Energy",
    setName: "Gym Challenge",
    cardNumber: "128/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 1430000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-014",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Farfetch'd",
    setName: "Base",
    cardNumber: "27/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 1530000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-015",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Rattata",
    setName: "Team Rocket",
    cardNumber: "66/82",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 1690000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-016",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Chinchou",
    setName: "Neo Revelation",
    cardNumber: "42/64",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 1750000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-017",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Chinchou",
    setName: "Neo Genesis",
    cardNumber: "55/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 1790000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-018",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Geodude",
    setName: "Neo Revelation",
    cardNumber: "44/64",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 1840000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-019",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Poliwhirl",
    setName: "Base",
    cardNumber: "38/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 1900000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-020",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Super Rod",
    setName: "Neo Genesis",
    cardNumber: "103/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 1930000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-021",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Blaine's Last Resort",
    setName: "Gym Heroes",
    cardNumber: "105/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 1990000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-022",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Ruin Wall",
    setName: "Neo Discovery",
    cardNumber: "74/75",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2030000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-023",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Granbull",
    setName: "Neo Genesis",
    cardNumber: "37/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2080000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-024",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Lt. Surge's Voltorb",
    setName: "Gym Challenge",
    cardNumber: "86/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2130000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-025",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Brock's Rhyhorn",
    setName: "Gym Heroes",
    cardNumber: "70/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2210000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-026",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Spearow",
    setName: "Jungle",
    cardNumber: "62/64",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2240000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-027",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Swinub",
    setName: "Neo Genesis",
    cardNumber: "79/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2290000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-028",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Unown [E]",
    setName: "Neo Discovery",
    cardNumber: "67/75",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2350000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-029",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Lt. Surge's Spearow",
    setName: "Gym Heroes",
    cardNumber: "83/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2420000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-030",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Diglett",
    setName: "Team Rocket",
    cardNumber: "52/82",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2520000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-031",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Hoppip",
    setName: "Neo Discovery",
    cardNumber: "55/75",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2570000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-032",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Erika's Paras",
    setName: "Gym Challenge",
    cardNumber: "71/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2590000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-033",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Mankey",
    setName: "Jungle",
    cardNumber: "55/64",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2660000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-034",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Koga's Koffing",
    setName: "Gym Challenge",
    cardNumber: "79/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2680000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-035",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Unown [K]",
    setName: "Neo Revelation",
    cardNumber: "58/64",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2710000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-036",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Potion Energy",
    setName: "Team Rocket",
    cardNumber: "82/82",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2750000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-037",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Koga's Zubat",
    setName: "Gym Challenge",
    cardNumber: "83/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2780000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-038",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Misty's Seel",
    setName: "Gym Challenge",
    cardNumber: "91/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2830000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-039",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Energy Charge",
    setName: "Neo Genesis",
    cardNumber: "85/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2870000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-040",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Tyrogue",
    setName: "Neo Discovery",
    cardNumber: "66/75",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2890000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-041",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Mareep",
    setName: "Neo Genesis",
    cardNumber: "65/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2920000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-042",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Maintenance",
    setName: "Base",
    cardNumber: "83/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2970000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-043",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Water Energy",
    setName: "Gym Challenge",
    cardNumber: "132/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 3070000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-044",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Kingler",
    setName: "Fossil",
    cardNumber: "38/62",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 3100000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-045",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Parasect",
    setName: "Neo Revelation",
    cardNumber: "35/64",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 3180000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-046",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Misty's Poliwag",
    setName: "Gym Heroes",
    cardNumber: "87/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 3240000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-047",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Rocket's Minefield Gym",
    setName: "Gym Challenge",
    cardNumber: "119/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 3290000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-048",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Lt. Surge's Raticate",
    setName: "Gym Challenge",
    cardNumber: "53/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 3350000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-049",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Lt. Surge's Spearow",
    setName: "Gym Heroes",
    cardNumber: "52/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 3400000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-050",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Misty's Staryu",
    setName: "Gym Challenge",
    cardNumber: "92/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 3490000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-051",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Horsea",
    setName: "Fossil",
    cardNumber: "49/62",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 3630000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-052",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Misty's Staryu",
    setName: "Gym Heroes",
    cardNumber: "90/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 3700000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-053",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Oddish",
    setName: "Team Rocket",
    cardNumber: "63/82",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 3820000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-054",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Koga's Grimer",
    setName: "Gym Challenge",
    cardNumber: "78/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 3920000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-055",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Lass",
    setName: "Base",
    cardNumber: "75/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 3970000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-056",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Dratini",
    setName: "Base",
    cardNumber: "26/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 4040000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-057",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Rhyhorn",
    setName: "Jungle",
    cardNumber: "61/64",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 4170000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-058",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Fearow",
    setName: "Jungle",
    cardNumber: "36/64",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 4320000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-059",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Blaine's Ponyta",
    setName: "Gym Heroes",
    cardNumber: "63/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 4420000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-060",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Sabrina's Drowzee",
    setName: "Gym Heroes",
    cardNumber: "92/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 4580000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-061",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Brock's Geodude",
    setName: "Gym Heroes",
    cardNumber: "38/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 4620000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-062",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Shuckle",
    setName: "Neo Genesis",
    cardNumber: "72/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 4710000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-063",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Erika's Bellsprout",
    setName: "Gym Challenge",
    cardNumber: "38/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 4790000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-064",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Voltorb",
    setName: "Base",
    cardNumber: "67/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 4840000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-065",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Dark Electrode",
    setName: "Team Rocket",
    cardNumber: "34/82",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 4950000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-066",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Koga's Tangela",
    setName: "Gym Challenge",
    cardNumber: "81/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 5090000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-067",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Lt. Surge's Raticate",
    setName: "Gym Heroes",
    cardNumber: "51/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 5190000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-068",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Unown [Y]",
    setName: "Neo Revelation",
    cardNumber: "40/64",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 5290000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-069",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Gambler",
    setName: "Fossil",
    cardNumber: "60/62",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 5470000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-070",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Super Energy Removal",
    setName: "Base",
    cardNumber: "79/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 5520000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-071",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Blaine's Vulpix",
    setName: "Gym Challenge",
    cardNumber: "66/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 5600000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-072",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Master Ball",
    setName: "Gym Challenge",
    cardNumber: "116/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 5680000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-073",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Misty's Seaking",
    setName: "Gym Heroes",
    cardNumber: "55/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 5910000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-074",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Magcargo",
    setName: "Neo Revelation",
    cardNumber: "33/64",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 6170000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-075",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Dark Gloom",
    setName: "Team Rocket",
    cardNumber: "36/82",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 6280000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-076",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Koga's Pidgey",
    setName: "Gym Challenge",
    cardNumber: "49/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 6410000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-077",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Brock's Onix",
    setName: "Gym Heroes",
    cardNumber: "69/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 6570000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-078",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Sabrina's Abra",
    setName: "Gym Challenge",
    cardNumber: "93/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 6640000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-079",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Slowpoke",
    setName: "Fossil",
    cardNumber: "55/62",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 6830000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-080",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Recycle Energy",
    setName: "Neo Genesis",
    cardNumber: "105/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 7010000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-081",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Caterpie",
    setName: "Neo Discovery",
    cardNumber: "53/75",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 7290000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-082",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Koga's Koffing",
    setName: "Gym Challenge",
    cardNumber: "48/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 7550000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-083",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Octillery",
    setName: "Neo Revelation",
    cardNumber: "34/64",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 7830000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-084",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Lickitung",
    setName: "Jungle",
    cardNumber: "38/64",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 8000000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-085",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Sandslash",
    setName: "Fossil",
    cardNumber: "41/62",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 8180000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-086",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Gastly",
    setName: "Fossil",
    cardNumber: "33/62",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 8480000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-087",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Arcade Game",
    setName: "Neo Genesis",
    cardNumber: "83/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 8750000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-088",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Magikarp",
    setName: "Team Rocket",
    cardNumber: "47/82",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 8970000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-089",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Murkrow",
    setName: "Neo Genesis",
    cardNumber: "24/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 9260000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-090",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Blaine's Kangaskhan",
    setName: "Gym Heroes",
    cardNumber: "36/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 9430000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-091",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Brock's Lickitung",
    setName: "Gym Heroes",
    cardNumber: "41/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 9960000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-092",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Misty's Starmie",
    setName: "Gym Heroes",
    cardNumber: "56/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 10800000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-093",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Darkness Energy",
    setName: "Neo Genesis",
    cardNumber: "104/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 10900000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-094",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Pidgeotto",
    setName: "Base",
    cardNumber: "22/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 11520000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-095",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Blaine's Growlithe",
    setName: "Gym Challenge",
    cardNumber: "62/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 11920000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-096",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Rhydon",
    setName: "Jungle",
    cardNumber: "45/64",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 12280000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-097",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Sabrina's Abra",
    setName: "Gym Challenge",
    cardNumber: "94/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 12500000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-098",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Bayleef",
    setName: "Neo Genesis",
    cardNumber: "28/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 12830000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-099",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Omanyte",
    setName: "Neo Discovery",
    cardNumber: "60/75",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 13090000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-100",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Squirtle",
    setName: "Team Rocket",
    cardNumber: "68/82",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 13410000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-101",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Yanma",
    setName: "Neo Discovery",
    cardNumber: "36/75",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 13580000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-102",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Persian",
    setName: "Jungle",
    cardNumber: "42/64",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 13890000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-103",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Erika's Weepinbell",
    setName: "Gym Heroes",
    cardNumber: "48/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 14050000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-104",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Dark Golbat",
    setName: "Team Rocket",
    cardNumber: "24/82",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 14440000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-105",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Sabrina's Gastly",
    setName: "Gym Challenge",
    cardNumber: "97/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 14770000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-106",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Dark Dragonair",
    setName: "Team Rocket",
    cardNumber: "33/82",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 15370000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-107",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Igglybuff",
    setName: "Neo Discovery",
    cardNumber: "40/75",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 15820000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-108",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Dark Machamp",
    setName: "Team Rocket",
    cardNumber: "27/82",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 16110000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-109",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Victreebel",
    setName: "Jungle",
    cardNumber: "30/64",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 16390000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-110",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Erika's Gloom",
    setName: "Gym Heroes",
    cardNumber: "46/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 16790000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-111",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Erika's Jigglypuff",
    setName: "Gym Challenge",
    cardNumber: "69/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 17590000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-112",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Kangaskhan",
    setName: "Jungle",
    cardNumber: "21/64",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 18130000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-113",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Giovanni",
    setName: "Gym Challenge",
    cardNumber: "104/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 18960000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-114",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Mr. Mime",
    setName: "Jungle",
    cardNumber: "22/64",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 19730000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-115",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Nidoqueen",
    setName: "Jungle",
    cardNumber: "23/64",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 20180000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-116",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Aerodactyl",
    setName: "Fossil",
    cardNumber: "16/62",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 21170000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-117",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Brock's Sandslash",
    setName: "Gym Heroes",
    cardNumber: "23/132",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 21970000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-118",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Kabuto",
    setName: "Fossil",
    cardNumber: "50/62",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 22570000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-119",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Haunter",
    setName: "Fossil",
    cardNumber: "21/62",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 23410000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-120",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Zapdos",
    setName: "Fossil",
    cardNumber: "30/62",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 24130000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-121",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Beedrill",
    setName: "Neo Discovery",
    cardNumber: "18/75",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 24850000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-122",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Giovanni's Pinsir",
    setName: "Gym Challenge",
    cardNumber: "24/132",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 25760000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-123",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Misty",
    setName: "Gym Heroes",
    cardNumber: "102/132",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 26320000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-124",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Skarmory",
    setName: "Neo Revelation",
    cardNumber: "23/64",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 27930000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-125",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Scyther",
    setName: "Jungle",
    cardNumber: "26/64",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 30660000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-126",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Giovanni's Nidoqueen",
    setName: "Gym Challenge",
    cardNumber: "23/132",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 31930000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-127",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Togepi",
    setName: "Neo Genesis",
    cardNumber: "51/111",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 32640000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-128",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Raichu",
    setName: "Neo Revelation",
    cardNumber: "21/64",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 35960000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-129",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Misty's Wish",
    setName: "Gym Challenge",
    cardNumber: "108/132",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 37470000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-130",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Poliwrath",
    setName: "Base",
    cardNumber: "13/102",
    language: "en",
    finish: "holofoil",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 41530000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-131",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Dark Weezing",
    setName: "Team Rocket",
    cardNumber: "14/82",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 46500000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-132",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Sabrina's Haunter",
    setName: "Gym Challenge",
    cardNumber: "55/132",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 47780000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-133",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Koga",
    setName: "Gym Challenge",
    cardNumber: "19/132",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 49990000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-134",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Muk",
    setName: "Fossil",
    cardNumber: "13/62",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 54560000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-135",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Dark Arbok",
    setName: "Team Rocket",
    cardNumber: "2/82",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 61550000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-136",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Forretress",
    setName: "Neo Discovery",
    cardNumber: "2/75",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 65000000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-137",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Alakazam",
    setName: "Base",
    cardNumber: "1/102",
    language: "en",
    finish: "holofoil",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 71510000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-138",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Dark Dragonite",
    setName: "Team Rocket",
    cardNumber: "22/82",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 73960000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-139",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Skarmory",
    setName: "Neo Genesis",
    cardNumber: "13/111",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 77520000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-140",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Aerodactyl",
    setName: "Fossil",
    cardNumber: "1/62",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 82420000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-141",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Brock",
    setName: "Gym Heroes",
    cardNumber: "15/132",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 83390000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-142",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Unown [A]",
    setName: "Neo Discovery",
    cardNumber: "14/75",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 84990000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-143",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Lt. Surge's Magneton",
    setName: "Gym Heroes",
    cardNumber: "8/132",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 87370000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-144",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Vileplume",
    setName: "Jungle",
    cardNumber: "15/64",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 90970000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-145",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Gengar",
    setName: "Fossil",
    cardNumber: "20/62",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 97680000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-146",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Giovanni",
    setName: "Gym Challenge",
    cardNumber: "18/132",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 99090000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-147",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Ursaring",
    setName: "Neo Discovery",
    cardNumber: "15/75",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 100400000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-148",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Nidoqueen",
    setName: "Jungle",
    cardNumber: "7/64",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 108570000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-149",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Smeargle",
    setName: "Neo Discovery",
    cardNumber: "11/75",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 117490000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-150",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Kabutops",
    setName: "Neo Discovery",
    cardNumber: "6/75",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 124740000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-151",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Rocket's Hitmonchan",
    setName: "Gym Heroes",
    cardNumber: "11/132",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 135710000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-152",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Scyther",
    setName: "Jungle",
    cardNumber: "10/64",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 142740000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-153",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Brock's Ninetales",
    setName: "Gym Challenge",
    cardNumber: "3/132",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 145000000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-154",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Dark Alakazam",
    setName: "Team Rocket",
    cardNumber: "1/82",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 169150000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-155",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Dark Charizard",
    setName: "Team Rocket",
    cardNumber: "21/82",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 175720000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-156",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Hitmontop",
    setName: "Neo Discovery",
    cardNumber: "3/75",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 192450000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-157",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Articuno",
    setName: "Fossil",
    cardNumber: "2/62",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 202490000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-158",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Meganium",
    setName: "Neo Genesis",
    cardNumber: "11/111",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 229530000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-159",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Sabrina's Alakazam",
    setName: "Gym Challenge",
    cardNumber: "16/132",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 259250000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-160",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Giovanni's Gyarados",
    setName: "Gym Challenge",
    cardNumber: "5/132",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 321990000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-161",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Celebi",
    setName: "Neo Revelation",
    cardNumber: "3/64",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 349990000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-162",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Dark Raichu",
    setName: "Team Rocket",
    cardNumber: "83/82",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 352750000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-163",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Blaine's Arcanine",
    setName: "Gym Challenge",
    cardNumber: "1/132",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 355790000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-164",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Erika's Dragonair",
    setName: "Gym Heroes",
    cardNumber: "4/132",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 387000000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-165",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Dark Dragonite",
    setName: "Team Rocket",
    cardNumber: "5/82",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 403990000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-166",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Dark Blastoise",
    setName: "Team Rocket",
    cardNumber: "3/82",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 418000000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-167",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Houndoom",
    setName: "Neo Revelation",
    cardNumber: "8/64",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 439990000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-168",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Dark Charizard",
    setName: "Team Rocket",
    cardNumber: "4/82",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 444290000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-169",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Tyranitar",
    setName: "Neo Discovery",
    cardNumber: "12/75",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 450000000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-170",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Suicune",
    setName: "Neo Revelation",
    cardNumber: "14/64",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 460700000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-171",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Dragonite",
    setName: "Fossil",
    cardNumber: "4/62",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 461750000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-172",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Ho-oh",
    setName: "Neo Revelation",
    cardNumber: "7/64",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 488520000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-173",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Raikou",
    setName: "Neo Revelation",
    cardNumber: "13/64",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 498990000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-174",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Entei",
    setName: "Neo Revelation",
    cardNumber: "6/64",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 500000000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-175",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Sabrina's Gengar",
    setName: "Gym Heroes",
    cardNumber: "14/132",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 1,
    priceUsdcBaseUnits: 600870000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-176",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Gengar",
    setName: "Fossil",
    cardNumber: "5/62",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 1,
    priceUsdcBaseUnits: 601490000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-177",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Blaine's Charizard",
    setName: "Gym Challenge",
    cardNumber: "2/132",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 1,
    priceUsdcBaseUnits: 699990000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-178",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Typhlosion",
    setName: "Neo Genesis",
    cardNumber: "18/111",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 1,
    priceUsdcBaseUnits: 699990000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-179",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Charizard",
    setName: "Base",
    cardNumber: "4/102",
    language: "en",
    finish: "holofoil",
    condition: "mint",
    quantityAvailable: 1,
    priceUsdcBaseUnits: 800430000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-180",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Lugia",
    setName: "Neo Genesis",
    cardNumber: "9/111",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 1,
    priceUsdcBaseUnits: 1299960000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg001",
    externalSellerId: "mock-seller-01",
    cardGame: "yugioh",
    cardName: "Feral Imp",
    setName: "Dark Beginning 1",
    cardNumber: "DB1-EN140",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 80000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg002",
    externalSellerId: "mock-seller-02",
    cardGame: "yugioh",
    cardName: "Mystical Elf",
    setName: "2-Player Starter Deck: Yuya & Declan",
    cardNumber: "YS15-ENY02",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 100000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg003",
    externalSellerId: "mock-seller-03",
    cardGame: "yugioh",
    cardName: "Buster Blader",
    setName: "Anniversary Pack",
    cardNumber: "YAP1-EN006",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 100000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg004",
    externalSellerId: "mock-seller-04",
    cardGame: "yugioh",
    cardName: "Baby Dragon",
    setName: "Dark Beginning 2",
    cardNumber: "DB2-EN035",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 120000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg005",
    externalSellerId: "mock-seller-05",
    cardGame: "yugioh",
    cardName: "Blue-Eyes White Dragon",
    setName: "2016 Mega-Tins",
    cardNumber: "CT13-EN008",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 160000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg006",
    externalSellerId: "mock-seller-01",
    cardGame: "yugioh",
    cardName: "Winged Kuriboh",
    setName: "25th Anniversary Tin: Dueling Mirrors",
    cardNumber: "MP24-EN017",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 160000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg007",
    externalSellerId: "mock-seller-02",
    cardGame: "yugioh",
    cardName: "Man-Eater Bug",
    setName: "Dark Beginning 1",
    cardNumber: "DB1-EN131",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 160000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg008",
    externalSellerId: "mock-seller-03",
    cardGame: "yugioh",
    cardName: "Judge Man",
    setName: "25th Anniversary Ultimate Kaiba Set",
    cardNumber: "KC01-EN006",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 180000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg009",
    externalSellerId: "mock-seller-04",
    cardGame: "yugioh",
    cardName: "Red-Eyes Black Dragon",
    setName: "25th Anniversary Tin: Dueling Mirrors",
    cardNumber: "MP24-EN054",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 190000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg010",
    externalSellerId: "mock-seller-05",
    cardGame: "yugioh",
    cardName: "Kuriboh",
    setName: "Brothers of Legend",
    cardNumber: "BROL-EN062",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 200000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg011",
    externalSellerId: "mock-seller-01",
    cardGame: "yugioh",
    cardName: "Monster Reborn",
    setName: "2019 Gold Sarcophagus Tin",
    cardNumber: "TN19-EN011",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 200000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg012",
    externalSellerId: "mock-seller-02",
    cardGame: "yugioh",
    cardName: "Gaia The Fierce Knight",
    setName: "Dark Beginning 1",
    cardNumber: "DB1-EN103",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 240000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg013",
    externalSellerId: "mock-seller-03",
    cardGame: "yugioh",
    cardName: "Dark Magician",
    setName: "2016 Mega-Tins",
    cardNumber: "CT13-EN003",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 270000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg014",
    externalSellerId: "mock-seller-04",
    cardGame: "yugioh",
    cardName: "Celtic Guardian",
    setName: "Anniversary Pack",
    cardNumber: "YAP1-EN004",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 330000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg015",
    externalSellerId: "mock-seller-05",
    cardGame: "yugioh",
    cardName: "Time Wizard",
    setName: "Dark Beginning 2",
    cardNumber: "DB2-EN038",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 370000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg016",
    externalSellerId: "mock-seller-01",
    cardGame: "yugioh",
    cardName: "Summoned Skull",
    setName: "Anniversary Pack",
    cardNumber: "YAP1-EN003",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 540000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg017",
    externalSellerId: "mock-seller-02",
    cardGame: "yugioh",
    cardName: "Mirror Force",
    setName: "2-Player Starter Deck: Yuya & Declan",
    cardNumber: "YS15-END16",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 660000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg018",
    externalSellerId: "mock-seller-03",
    cardGame: "yugioh",
    cardName: "Black Luster Soldier",
    setName: "Duel Terminal 7a",
    cardNumber: "DT07-EN030",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 950000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg019",
    externalSellerId: "mock-seller-04",
    cardGame: "yugioh",
    cardName: "Exodia the Forbidden One",
    setName: "25th Anniversary Tin: Dueling Heroes",
    cardNumber: "TN23-EN002",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2290000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg020",
    externalSellerId: "mock-seller-05",
    cardGame: "yugioh",
    cardName: "Pot of Greed",
    setName: "2025 Mega-Pack Tin",
    cardNumber: "MP25-EN050",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 4370000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
];
