import type { SupplierEligibleListing } from "../types";

/**
 * Deterministic fixture inventory for CARDTRADER_MODE=mock (local dev, CI, and this repo's
 * test suite). Never used in production — see CARDTRADER_MODE in src/server/env.ts.
 *
 * Card names, sets, card numbers, finishes, and prices are real — 90 Pokemon cards pulled
 * from the live Pokemon TCG API (api.pokemontcg.io) across Base Set, Gym Heroes, and Neo
 * Genesis, plus 20 Yu-Gi-Oh cards pulled from the live YGOPRODeck API (db.ygoprodeck.com),
 * each using that card's real current tcgplayer.com market price at fetch time, converted
 * to USDC base units. This is still a MOCK CardTrader listing (quantities, seller IDs, and
 * reliability scores below are synthetic — CardTrader itself is not live yet, see
 * AGENTS.md) — only the card identity and reference price are real, snapshotted
 * 2026-08-02. Re-run scripts/refresh-mock-inventory (see docs/DECISIONS.md) to pull a
 * fresh snapshot.
 */
export const MOCK_CARDTRADER_INVENTORY: SupplierEligibleListing[] = [
  {
    externalListingId: "mock-listing-001",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Super Potion",
    setName: "Base",
    cardNumber: "90/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 330000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-002",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Grass Energy",
    setName: "Base",
    cardNumber: "99/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 450000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-003",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Fighting Energy",
    setName: "Base",
    cardNumber: "97/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 510000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-004",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Machop",
    setName: "Base",
    cardNumber: "52/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 580000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-005",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Weedle",
    setName: "Base",
    cardNumber: "69/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 660000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-006",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Ponyta",
    setName: "Base",
    cardNumber: "60/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 760000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-007",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Metapod",
    setName: "Base",
    cardNumber: "54/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 840000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-008",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Starmie",
    setName: "Base",
    cardNumber: "64/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 950000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-009",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Vulpix",
    setName: "Base",
    cardNumber: "68/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 1000000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-010",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Fighting Energy",
    setName: "Neo Genesis",
    cardNumber: "106/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 1110000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-011",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Gastly",
    setName: "Base",
    cardNumber: "50/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 1160000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-012",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Doduo",
    setName: "Base",
    cardNumber: "48/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 1280000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-013",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Kakuna",
    setName: "Base",
    cardNumber: "33/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 1430000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-014",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Abra",
    setName: "Base",
    cardNumber: "43/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 1760000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-015",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Gligar",
    setName: "Neo Genesis",
    cardNumber: "59/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 1870000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-016",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Mantine",
    setName: "Neo Genesis",
    cardNumber: "64/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 1930000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-017",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Natu",
    setName: "Neo Genesis",
    cardNumber: "67/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2020000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-018",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Celadon City Gym",
    setName: "Gym Heroes",
    cardNumber: "107/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2090000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-019",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Brock's Rhyhorn",
    setName: "Gym Heroes",
    cardNumber: "70/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2210000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-020",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Erika's Bellsprout",
    setName: "Gym Heroes",
    cardNumber: "76/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2330000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-021",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Ledian",
    setName: "Neo Genesis",
    cardNumber: "39/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2430000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-022",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Stantler",
    setName: "Neo Genesis",
    cardNumber: "76/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2650000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-023",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Lt. Surge's Rattata",
    setName: "Gym Heroes",
    cardNumber: "82/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2670000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-024",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Time Capsule",
    setName: "Neo Genesis",
    cardNumber: "90/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2730000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-025",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Card-Flip Game",
    setName: "Neo Genesis",
    cardNumber: "92/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2830000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-026",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Charmander",
    setName: "Base",
    cardNumber: "46/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2920000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-027",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Maintenance",
    setName: "Base",
    cardNumber: "83/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2970000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-028",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Seadra",
    setName: "Neo Genesis",
    cardNumber: "48/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 3110000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-029",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Piloswine",
    setName: "Neo Genesis",
    cardNumber: "44/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 3190000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-030",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Professor Elm",
    setName: "Neo Genesis",
    cardNumber: "96/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 3290000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-031",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Lt. Surge's Spearow",
    setName: "Gym Heroes",
    cardNumber: "52/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 3400000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-032",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Gold Berry",
    setName: "Neo Genesis",
    cardNumber: "93/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 3630000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-033",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Charmeleon",
    setName: "Base",
    cardNumber: "24/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 3730000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-034",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Sunflora",
    setName: "Neo Genesis",
    cardNumber: "50/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 3930000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-035",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Brock's Graveler",
    setName: "Gym Heroes",
    cardNumber: "40/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 4090000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-036",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Ariados",
    setName: "Neo Genesis",
    cardNumber: "27/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 4330000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-037",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Magmar",
    setName: "Neo Genesis",
    cardNumber: "40/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 4490000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-038",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Sudowoodo",
    setName: "Neo Genesis",
    cardNumber: "77/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 4690000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-039",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Wartortle",
    setName: "Base",
    cardNumber: "42/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 4830000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-040",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Sabrina's Abra",
    setName: "Gym Heroes",
    cardNumber: "91/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 5060000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-041",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Lt. Surge's Raticate",
    setName: "Gym Heroes",
    cardNumber: "51/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 5190000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-042",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Super Energy Removal",
    setName: "Base",
    cardNumber: "79/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 5520000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-043",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Devolution Spray",
    setName: "Base",
    cardNumber: "72/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 5920000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-044",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Flaaffy",
    setName: "Neo Genesis",
    cardNumber: "34/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 6250000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-045",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Pokémon Breeder",
    setName: "Base",
    cardNumber: "76/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 6540000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-046",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Brock's Vulpix",
    setName: "Gym Heroes",
    cardNumber: "73/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 6890000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-047",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Erika's Gloom",
    setName: "Gym Heroes",
    cardNumber: "45/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 7190000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-048",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Pikachu",
    setName: "Base",
    cardNumber: "58/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 7710000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-049",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Erika's Oddish",
    setName: "Gym Heroes",
    cardNumber: "47/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 8050000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-050",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Arcade Game",
    setName: "Neo Genesis",
    cardNumber: "83/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 8750000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-051",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Blaine's Magmar",
    setName: "Gym Heroes",
    cardNumber: "37/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 9220000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-052",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Lt. Surge",
    setName: "Gym Heroes",
    cardNumber: "101/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 9570000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-053",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "No Removal Gym",
    setName: "Gym Heroes",
    cardNumber: "103/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 10580000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-054",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Darkness Energy",
    setName: "Neo Genesis",
    cardNumber: "104/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 10900000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-055",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Magby",
    setName: "Neo Genesis",
    cardNumber: "23/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 11540000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-056",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Blaine's Charmander",
    setName: "Gym Heroes",
    cardNumber: "61/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 12790000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-057",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Misty's Goldeen",
    setName: "Gym Heroes",
    cardNumber: "30/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 13530000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-058",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Erika's Weepinbell",
    setName: "Gym Heroes",
    cardNumber: "48/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 14050000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-059",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Misty's Tentacool",
    setName: "Gym Heroes",
    cardNumber: "32/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 15280000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-060",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Focus Band",
    setName: "Neo Genesis",
    cardNumber: "86/111",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 16500000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-061",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Lt. Surge's Electabuzz",
    setName: "Gym Heroes",
    cardNumber: "27/132",
    language: "en",
    finish: "first_edition",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 17570000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-062",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Dragonair",
    setName: "Base",
    cardNumber: "18/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 18360000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-063",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Cleffa",
    setName: "Neo Genesis",
    cardNumber: "20/111",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 22400000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-064",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Erika's Clefairy",
    setName: "Gym Heroes",
    cardNumber: "25/132",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 25740000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-065",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Metal Energy",
    setName: "Neo Genesis",
    cardNumber: "19/111",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 28000000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-066",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Magneton",
    setName: "Base",
    cardNumber: "9/102",
    language: "en",
    finish: "holofoil",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 35320000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-067",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Nidoking",
    setName: "Base",
    cardNumber: "11/102",
    language: "en",
    finish: "holofoil",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 37960000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-068",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "The Rocket's Trap",
    setName: "Gym Heroes",
    cardNumber: "19/132",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 8,
    priceUsdcBaseUnits: 48800000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-069",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Sabrina's Haunter",
    setName: "Gym Heroes",
    cardNumber: "58/132",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 58220000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-070",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Mewtwo",
    setName: "Base",
    cardNumber: "10/102",
    language: "en",
    finish: "holofoil",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 77270000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-071",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Erika's Vileplume",
    setName: "Gym Heroes",
    cardNumber: "5/132",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 83060000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-072",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Feraligatr",
    setName: "Neo Genesis",
    cardNumber: "5/111",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 85400000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-073",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Azumarill",
    setName: "Neo Genesis",
    cardNumber: "2/111",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 94250000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-074",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Lt. Surge's Fearow",
    setName: "Gym Heroes",
    cardNumber: "7/132",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 108250000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-075",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Misty's Seadra",
    setName: "Gym Heroes",
    cardNumber: "9/132",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 137610000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-076",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Blaine's Moltres",
    setName: "Gym Heroes",
    cardNumber: "1/132",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 185580000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-077",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Heracross",
    setName: "Neo Genesis",
    cardNumber: "6/111",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 192900000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-078",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Feraligatr",
    setName: "Neo Genesis",
    cardNumber: "4/111",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 200000000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-079",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Slowking",
    setName: "Neo Genesis",
    cardNumber: "14/111",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 202940000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-080",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Blastoise",
    setName: "Base",
    cardNumber: "2/102",
    language: "en",
    finish: "holofoil",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 224860000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-081",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Meganium",
    setName: "Neo Genesis",
    cardNumber: "11/111",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 229530000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-082",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Rocket's Moltres",
    setName: "Gym Heroes",
    cardNumber: "12/132",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 230630000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-083",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Pichu",
    setName: "Neo Genesis",
    cardNumber: "12/111",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 290450000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-084",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Typhlosion",
    setName: "Neo Genesis",
    cardNumber: "17/111",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 320500000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-085",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Rocket's Scyther",
    setName: "Gym Heroes",
    cardNumber: "13/132",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 349990000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-086",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Erika's Dragonair",
    setName: "Gym Heroes",
    cardNumber: "4/132",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 387000000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-087",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Sabrina's Gengar",
    setName: "Gym Heroes",
    cardNumber: "14/132",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 1,
    priceUsdcBaseUnits: 600870000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-088",
    externalSellerId: "mock-seller-03",
    cardGame: "pokemon",
    cardName: "Typhlosion",
    setName: "Neo Genesis",
    cardNumber: "18/111",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 1,
    priceUsdcBaseUnits: 699990000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-089",
    externalSellerId: "mock-seller-04",
    cardGame: "pokemon",
    cardName: "Charizard",
    setName: "Base",
    cardNumber: "4/102",
    language: "en",
    finish: "holofoil",
    condition: "mint",
    quantityAvailable: 1,
    priceUsdcBaseUnits: 800430000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-090",
    externalSellerId: "mock-seller-05",
    cardGame: "pokemon",
    cardName: "Lugia",
    setName: "Neo Genesis",
    cardNumber: "9/111",
    language: "en",
    finish: "first_edition",
    condition: "mint",
    quantityAvailable: 1,
    priceUsdcBaseUnits: 1299960000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg001",
    externalSellerId: "mock-seller-01",
    cardGame: "yugioh",
    cardName: "Feral Imp",
    setName: "Dark Beginning 1",
    cardNumber: "DB1-EN140",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 80000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg002",
    externalSellerId: "mock-seller-02",
    cardGame: "yugioh",
    cardName: "Mystical Elf",
    setName: "2-Player Starter Deck: Yuya & Declan",
    cardNumber: "YS15-ENY02",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 100000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg003",
    externalSellerId: "mock-seller-03",
    cardGame: "yugioh",
    cardName: "Buster Blader",
    setName: "Anniversary Pack",
    cardNumber: "YAP1-EN006",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 100000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg004",
    externalSellerId: "mock-seller-04",
    cardGame: "yugioh",
    cardName: "Baby Dragon",
    setName: "Dark Beginning 2",
    cardNumber: "DB2-EN035",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 120000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg005",
    externalSellerId: "mock-seller-05",
    cardGame: "yugioh",
    cardName: "Blue-Eyes White Dragon",
    setName: "2016 Mega-Tins",
    cardNumber: "CT13-EN008",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 160000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg006",
    externalSellerId: "mock-seller-01",
    cardGame: "yugioh",
    cardName: "Winged Kuriboh",
    setName: "25th Anniversary Tin: Dueling Mirrors",
    cardNumber: "MP24-EN017",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 160000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg007",
    externalSellerId: "mock-seller-02",
    cardGame: "yugioh",
    cardName: "Man-Eater Bug",
    setName: "Dark Beginning 1",
    cardNumber: "DB1-EN131",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 160000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg008",
    externalSellerId: "mock-seller-03",
    cardGame: "yugioh",
    cardName: "Judge Man",
    setName: "25th Anniversary Ultimate Kaiba Set",
    cardNumber: "KC01-EN006",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 180000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg009",
    externalSellerId: "mock-seller-04",
    cardGame: "yugioh",
    cardName: "Red-Eyes Black Dragon",
    setName: "25th Anniversary Tin: Dueling Mirrors",
    cardNumber: "MP24-EN054",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 190000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg010",
    externalSellerId: "mock-seller-05",
    cardGame: "yugioh",
    cardName: "Kuriboh",
    setName: "Brothers of Legend",
    cardNumber: "BROL-EN062",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 200000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg011",
    externalSellerId: "mock-seller-01",
    cardGame: "yugioh",
    cardName: "Monster Reborn",
    setName: "2019 Gold Sarcophagus Tin",
    cardNumber: "TN19-EN011",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 200000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg012",
    externalSellerId: "mock-seller-02",
    cardGame: "yugioh",
    cardName: "Gaia The Fierce Knight",
    setName: "Dark Beginning 1",
    cardNumber: "DB1-EN103",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 240000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg013",
    externalSellerId: "mock-seller-03",
    cardGame: "yugioh",
    cardName: "Dark Magician",
    setName: "2016 Mega-Tins",
    cardNumber: "CT13-EN003",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 270000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg014",
    externalSellerId: "mock-seller-04",
    cardGame: "yugioh",
    cardName: "Celtic Guardian",
    setName: "Anniversary Pack",
    cardNumber: "YAP1-EN004",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 330000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg015",
    externalSellerId: "mock-seller-05",
    cardGame: "yugioh",
    cardName: "Time Wizard",
    setName: "Dark Beginning 2",
    cardNumber: "DB2-EN038",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 370000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg016",
    externalSellerId: "mock-seller-01",
    cardGame: "yugioh",
    cardName: "Summoned Skull",
    setName: "Anniversary Pack",
    cardNumber: "YAP1-EN003",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 540000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg017",
    externalSellerId: "mock-seller-02",
    cardGame: "yugioh",
    cardName: "Mirror Force",
    setName: "2-Player Starter Deck: Yuya & Declan",
    cardNumber: "YS15-END16",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 660000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg018",
    externalSellerId: "mock-seller-03",
    cardGame: "yugioh",
    cardName: "Black Luster Soldier",
    setName: "Duel Terminal 7a",
    cardNumber: "DT07-EN030",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 950000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg019",
    externalSellerId: "mock-seller-04",
    cardGame: "yugioh",
    cardName: "Exodia the Forbidden One",
    setName: "25th Anniversary Tin: Dueling Heroes",
    cardNumber: "TN23-EN002",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 2290000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
  {
    externalListingId: "mock-listing-yg020",
    externalSellerId: "mock-seller-05",
    cardGame: "yugioh",
    cardName: "Pot of Greed",
    setName: "2025 Mega-Pack Tin",
    cardNumber: "MP25-EN050",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 4370000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 93,
    lastRefreshedAt: new Date("2026-08-02T00:00:00.000Z"),
  },
];
