import type { SupplierEligibleListing } from "../types";

/**
 * Deterministic fixture inventory for CARDTRADER_MODE=mock (local dev, CI, and this repo's
 * test suite). Never used in production — see CARDTRADER_MODE in src/server/env.ts.
 */
export const MOCK_CARDTRADER_INVENTORY: SupplierEligibleListing[] = [
  {
    externalListingId: "mock-listing-001",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Charmander",
    setName: "Base Set",
    cardNumber: "46/102",
    language: "en",
    finish: "normal",
    condition: "near_mint",
    quantityAvailable: 12,
    priceUsdcBaseUnits: 800_000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date(),
  },
  {
    externalListingId: "mock-listing-002",
    externalSellerId: "mock-seller-01",
    cardGame: "pokemon",
    cardName: "Pikachu",
    setName: "Base Set",
    cardNumber: "58/102",
    language: "en",
    finish: "normal",
    condition: "lightly_played",
    quantityAvailable: 20,
    priceUsdcBaseUnits: 1_500_000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 96,
    lastRefreshedAt: new Date(),
  },
  {
    externalListingId: "mock-listing-003",
    externalSellerId: "mock-seller-02",
    cardGame: "pokemon",
    cardName: "Charizard",
    setName: "Base Set",
    cardNumber: "4/102",
    language: "en",
    finish: "holofoil",
    condition: "near_mint",
    quantityAvailable: 2,
    priceUsdcBaseUnits: 250_000_000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 99,
    lastRefreshedAt: new Date(),
  },
  {
    externalListingId: "mock-listing-004",
    externalSellerId: "mock-seller-03",
    cardGame: "yugioh",
    cardName: "Dark Magician",
    setName: "Legend of Blue Eyes White Dragon",
    cardNumber: "LOB-005",
    language: "en",
    finish: "first_edition",
    condition: "near_mint",
    quantityAvailable: 4,
    priceUsdcBaseUnits: 12_000_000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 91,
    lastRefreshedAt: new Date(),
  },
  {
    externalListingId: "mock-listing-005",
    externalSellerId: "mock-seller-03",
    cardGame: "yugioh",
    cardName: "Blue-Eyes White Dragon",
    setName: "Legend of Blue Eyes White Dragon",
    cardNumber: "LOB-001",
    language: "en",
    finish: "first_edition",
    condition: "moderately_played",
    quantityAvailable: 1,
    priceUsdcBaseUnits: 45_000_000,
    shipsToCustomer: true,
    imageUsePermitted: true,
    sellerReliabilityScore: 91,
    lastRefreshedAt: new Date(),
  },
];
